### ISSUE TITLE
aliyun.sh在群晖中无法运行，请教要如何处理？

### ISSUE THREAD

**Issue by caifw** [cuteribs/ribsnetwork#1]
运行后出现以下错误
/volume1/aliyunddns/aliyun.sh: line 7: syntax error near unexpected token `newline'
/volume1/aliyunddns/aliyun.sh: line 7: `< !DOCTYPE html >'
使用notepad++检查代码后，没有发现特殊字符，现在的回车字符为“LF”
求解决办法

**Comment by Dulasssss** [comment]
出现这个问题， < !DOCTYPE html >
应该是下载的aliyun.sh有问题
下载到了HTML格式的文件
我用目标另存一样的问题

直接点开aliyun.sh自己复制一份就OK了。
