### ISSUE TITLE
aliyun.sh 群辉中可以执行，但是无法更新aliyun的记录

### ISSUE THREAD

**Issue by xinfeihe** [cuteribs/ribsnetwork#2]
看日志，提示的是“获取当前 IP...当前 IP 为 *.*.*.*.获取 www.example.com 的 IP...域名记录不存在, 添加 www.example.com 至 *.*.*.*...www.example.com 已指向 *.*.*.*.”
我用的是阿里的子用户AccessKeyId和AccessKeySecret，只有访问云解析的权限，是这个原因造成的吗？

**Comment by chenkangyang** [comment]
之前一直使用正常。和楼上同样的报错，前两天出现过。没有使用阿里子用户，用的是完全权限。
3.27后脚本返回成功指向，但没能更新阿里云的DNS云解析，今天运行脚本发生新的报错如下：

> 获取当前IP...
wget: unrecognized option `--no-check-certificate'

**Comment by XtosX** [comment]
这个版本好像与最新的aliyun有出入，脚本应该要更新。会添加重复的记录

**Comment by yuezhx** [comment]
看一下群晖的系统时间是否与标准时间不一致，如果时间不一致会导致调用api时认证失败。

**Comment by cuteribs-1** [comment]
主域名与子域名都需要 URLENCODE 之后再传入.
